---
[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Services"
  url = "/services"
  weight = 2

[[main]]
  name = "Security Components"
  url = "/#security-components"
  weight = 3

[[main]]
  name = "About"
  url = "/about"
  weight = 4

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 5
---