# Site metadata
logo = "/images/logo.png"
logo_darkmode = "/images/logo-darkmode.png"
logo_width = "150px"
logo_height = "30px"
logo_text = "Thee Cloud"

# Site description
description = "Your cloud infrastructure security partner"

# Author
[author]
  name = "Thee Cloud"
  email = "hello@thee.cloud"

# Contact info
[contact_info]
  address = "Sydney, Australia"
  email = "hello@thee.cloud"

